variables: &variables
  SFOS_VERSION: 3.4.0.24
  CARGO_HOME: $CI_PROJECT_DIR/cargo

include:
  # Awesome OpenRepos script by @nobodyinperson/Yann Büchau
  - https://gitlab.com/nobodyinperson/python3-openrepos-webclient/-/raw/master/openrepos-upload-rpm.gitlab-ci.yml
  # The MergeRequest-Pipelines template makes your pipelines run for the default branch, tags, and all types of merge request pipelines.
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

stages:
  - build
  - test
  - format
  - deploy

.build-target: &build-target
  image: registry.gitlab.com/whisperfish/sailo-rs/platform-$MER_ARCH-$SFOS_VERSION:latest
  stage: build
  artifacts:
    paths:
      - target/*/release/rpmbuild/RPMS/*/*.rpm
      - target/*/release/whisperfish-migration-dry-run
      - target/*/release/fetch-signal-attachment
      - target/*/release/harbour-whisperfish
  cache:
    paths:
      - target
      - $CARGO_HOME/bin/
      - $CARGO_HOME/registry/index/
      - $CARGO_HOME/registry/cache/
      - $CARGO_HOME/git/db/
    key:
      files:
        - Cargo.lock
      prefix: target-$MER_ARCH
  script:
    - .ci/build-for-target.sh

build:armv7hl:
  variables:
    <<: *variables
    MER_ARCH: armv7hl
    RUST_ARCH: armv7-unknown-linux-gnueabihf
    CC_armv7_unknown_linux_gnueabihf: arm-linux-gnueabihf-gcc
    CXX_armv7_unknown_linux_gnueabihf: arm-linux-gnueabihf-g++
  <<: *build-target

build:i486:
  variables:
    <<: *variables
    MER_ARCH: i486
    RUST_ARCH: i686-unknown-linux-gnu
    CC_i686_unknown_linux_gnu: i686-linux-gnu-gcc
    CXX_i686_unknown_linux_gnu: i686-linux-gnu-g++
  <<: *build-target

build:aarch64:
  variables:
    <<: *variables
    MER_ARCH: aarch64
    RUST_ARCH: aarch64-unknown-linux-gnu
    CC_aarch64_unknown_linux_gnueabihf: aarch64-linux-gnu-gcc
    CXX_aarch64_unknown_linux_gnueabihf: aarch64-linux-gnu-g++
  <<: *build-target

.rust: &rust
  cache: &rust-cache
    paths:
      - target/
      - $CARGO_HOME/bin/
      - $CARGO_HOME/registry/index/
      - $CARGO_HOME/registry/cache/
      - $CARGO_HOME/git/db/
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends libsqlcipher-dev qtbase5-dev qtbase5-private-dev qt5-qmake cmake qtdeclarative5-dev qt5-default protobuf-compiler libdbus-1-dev libqt5opengl5-dev libssl-dev
    - cargo --version
    - rustc --version

.rust-stable: &rust-stable
  <<: *rust
  image: rust
  cache:
    <<: *rust-cache
    key:
      prefix: rust-stable
      files:
        - Cargo.lock

.rust-nightly: &rust-nightly
  <<: *rust
  image: rustlang/rust:nightly
  allow_failure: true
  cache:
    <<: *rust-cache
    key:
      prefix: rust-nightly
      files:
        - Cargo.lock

build:host:stable:
  <<: *rust-stable
  stage: build
  script:
    - cargo build

build:host:nightly:
  <<: *rust-nightly
  stage: build
  needs:
    # Run only if stable already succeeded. We don't use the results of this
    # job and run it only to test future versions of rust. See the discussion
    # in https://gitlab.com/whisperfish/whisperfish/-/merge_requests/202
    - build:host:stable
  script:
    - cargo build

build:host:stable:docs:
  <<: *rust-stable
  stage: build
  needs:
    - build:host:stable
  script:
    - cargo doc --no-deps --document-private-items -p harbour-whisperfish -p libsignal-service -p libsignal-protocol -p zkgroup 
  artifacts:
    paths:
      - target/doc
  # This job has no large overhead. Thus, we fetch only the cache from the
  # build job and don't interfere with later tests jobs.
  cache:
    <<: *rust-cache
    key:
      prefix: rust-stable
      files:
        - Cargo.lock
    policy: pull

qmllint:
  <<: *rust
  stage: format
  image: rust
  cache: {}
  script:
    - "qmllint qml/**/*.qml"

test:stable:
  <<: *rust-stable
  stage: test
  needs:
    - build:host:stable
  script:
    - cargo test

test:stable:diesel-schema:
  <<: *rust-stable
  stage: test
  needs:
    - build:host:stable
  script:
    - rustup component add rustfmt
    # Diesel is not running a long time/often. We don't need the release
    # version here and the debug version is enough. We save a lot of
    # compilation time for small overhead when running the binary.
    - cargo install -f --debug diesel_cli
    - export PATH="$CARGO_HOME/bin:$PATH"
    - export DATABASE_URL=test_whisperfish.db
    - diesel setup
    - diesel migration run
    - diesel print-schema > src/schema.rs
    - cargo fmt -- --check src/schema.rs
  # Diesel does not need to access build artifacts of other stages.
  cache: {}

fmt:stable:
  <<: *rust-stable
  stage: format
  needs:
    - build:host:stable
  # Cargo fmt does not need external packages.
  before_script: []
  script:
    - rustup component add rustfmt
    - cargo fmt -- --check
  # Cargo fmt does not need to access the cache. With it's own cache, it does
  # not interfere with `coverage:stable` and `clippy:stable`. There is nothing
  # to store in the cache either.
  cache: {}

coverage:stable:
  <<: *rust-stable
  image: xd009642/tarpaulin
  stage: format
  needs:
    - test:stable
  script:
    # Add --all-features and --all-targets some time in the future. Tarpaulin
    # runs only at linux-x86 and would need the whisperfish sdk to build all
    # features.
    - cargo tarpaulin -v --exclude-files cargo/* --out Xml
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    reports:
      cobertura: cobertura.xml
  coverage: '/^\d+.\d+% coverage/'
  # Tarpaulin needs its own cache as many more information are stored from
  # other crates. In addition, `clippy:stable` can pull/push the cache from
  # `test:stable` and the tarpaulin job does not interfere with the clippy
  # cache.
  cache:
    <<: *rust-cache
    key:
      prefix: rust-stable-tarpaulin
      files:
        - Cargo.lock

clippy:stable:
  <<: *rust-stable
  stage: format
  needs:
    - test:stable
  script:
    - rustup component add clippy
    # the following command should be used but needs sailfish SDK
    # - cargo clippy --all-targets --all-features -- -D warnings
    - cargo clippy --all-targets -- -D warnings

.translations: &translations
  image: debian
  needs: []
  before_script:
    - apt-get update
    - apt-get install --no-install-recommends -y git curl qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools qttools5-dev-tools

translations:check:
  <<: *translations
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
  script:
    - .ci/check-translations.sh

translations:update:
  <<: *translations
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - .ci/update-translations.sh

test:validate-rpms:
  stage: test
  image: registry.gitlab.com/whisperfish/sailo-rs/rpm-validator:latest
  allow_failure: true
  dependencies:
    - build:armv7hl
    - build:aarch64
    - build:i486
  needs:
    - build:armv7hl
    - build:aarch64
    - build:i486
  script:
    - rpmvalidation.sh target/armv7-unknown-linux-gnueabihf/release/rpmbuild/RPMS/armv7hl/*.rpm
    - rpmvalidation.sh target/i686-unknown-linux-gnu/release/rpmbuild/RPMS/i486/*.rpm
    - rpmvalidation.sh target/aarch64-unknown-linux-gnu/release/rpmbuild/RPMS/aarch64/*.rpm

notify_matrix_build_ready:
  stage: deploy
  image: debian
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  environment:
    name: Whisperfish Matrix channel
    url: $MATRIX_HOME_SERVER
  needs:
    - build:armv7hl
    - build:aarch64
    - build:i486
  before_script:
    - apt-get update
    - apt-get install --no-install-recommends -y git curl jq ca-certificates
  script:
    - .ci/send-matrix-build-notification.sh

pages:
  dependencies:
    - build:host:stable:docs
  needs:
    - build:host:stable:docs
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - mkdir -p public
    - mv target/doc public/
  artifacts:
    paths:
      - public

openrepos-deploy:
  stage: deploy
  extends: .openrepos-upload-rpm
  variables:
    OPENREPOS_UPLOAD_RPM_APPNAME:  Whisperfish
    OPENREPOS_UPLOAD_RPM_PLATFORM: SailfishOS
    OPENREPOS_UPLOAD_RPM_CATEGORY: Applications
    OPENREPOS_ACTION_DELAY: 3
  environment:
      name: OpenRepos
      url: https://openrepos.net/content/rubdos/whisperfish
  before_script:
    - mv target/armv7-unknown-linux-gnueabihf/release/rpmbuild/RPMS/armv7hl/*.rpm .
    - mv target/i686-unknown-linux-gnu/release/rpmbuild/RPMS/i486/*.rpm .
    - mv target/aarch64-unknown-linux-gnu/release/rpmbuild/RPMS/aarch64/*.rpm  .
    - ls *.rpm
  needs:
    - build:armv7hl
    - build:i486
    - build:aarch64
    - test:stable
  dependencies:
    - build:armv7hl
    - build:i486
    - build:aarch64
  only:
    - tags

dry-run:triage:
  stage: test
  image: ruby:2.4
  script:
    - gem install gitlab-triage
    - gitlab-triage --help
    - gitlab-triage --dry-run --token $PRIVATE_TOKEN --source projects --source-id $CI_PROJECT_PATH
  when: manual

policy:run:
  stage: deploy
  image: ruby:2.4
  script:
    - gem install gitlab-triage
    - gitlab-triage --token $PRIVATE_TOKEN --source projects --source-id $CI_PROJECT_PATH
  when: manual

schedule:policyrun:
  stage: deploy
  image: ruby:2.4
  script:
    - gem install gitlab-triage
    - gitlab-triage --token $PRIVATE_TOKEN --source projects --source-id $CI_PROJECT_PATH
  only:
    - schedules
