variables: &variables
  SFOS_VERSION: 4.1.0.23
  CARGO_HOME: /home/mersdk/cargo
  GIT_FETCH_EXTRA_FLAGS: --tags

include:
  # Awesome OpenRepos script by @nobodyinperson/Yann Büchau
  - https://gitlab.com/nobodyinperson/python3-openrepos-webclient/-/raw/master/openrepos-upload-rpm.gitlab-ci.yml
  # The MergeRequest-Pipelines template makes your pipelines run for the default branch, tags, and all types of merge request pipelines.
  # Use this template if you use any of the the pipelines for merge requests features. 
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

stages:
  - build
  - test
  - format
  - deploy

.build-sailfishos: &build-sailfishos
  image: registry.gitlab.com/whisperfish/sailo-rs/rust-$MER_ARCH-$SFOS_VERSION:latest
  stage: build
  artifacts:
    paths:
      - RPMS/*.rpm
        # i686 is the "native" target, so we catch them in the `target` dir directly.
      - target/release/whisperfish-migration-dry-run
      - target/release/fetch-signal-attachment
      - target/release/harbour-whisperfish
      - target/*/release/whisperfish-migration-dry-run
      - target/*/release/fetch-signal-attachment
      - target/*/release/harbour-whisperfish
  cache:
    paths:
      - target
      - $CARGO_HOME/bin/
      - $CARGO_HOME/registry/index/
      - $CARGO_HOME/registry/cache/
      - $CARGO_HOME/git/db/
    key:
      files:
        - Cargo.lock
      prefix: target-$MER_ARCH
  script:
    - .ci/build-with-mb2.sh

build:sailfishos:armv7hl:
  variables:
    <<: *variables
    MER_ARCH: armv7hl
  <<: *build-sailfishos

build:sailfishos:i486:
  variables:
    <<: *variables
    MER_ARCH: i486
  <<: *build-sailfishos

build:sailfishos:aarch64:
  variables:
    <<: *variables
    MER_ARCH: aarch64
  <<: *build-sailfishos

.rust: &rust
  cache: &rust-cache
    paths:
      - target/
      - $CARGO_HOME/bin/
      - $CARGO_HOME/registry/index/
      - $CARGO_HOME/registry/cache/
      - $CARGO_HOME/git/db/
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends libsqlcipher-dev qtbase5-dev qtbase5-private-dev qt5-qmake cmake qtdeclarative5-dev qt5-default protobuf-compiler libdbus-1-dev libqt5opengl5-dev 
    - cargo --version
    - rustc --version

.rust-stable: &rust-stable
  <<: *rust
  image: rust
  cache:
    <<: *rust-cache
    key:
      files:
        - Cargo.lock
      prefix: rust-stable

.rust-nightly: &rust-nightly
  <<: *rust
  image: rustlang/rust:nightly
  allow_failure: true
  cache:
    <<: *rust-cache
    key:
      files:
        - Cargo.lock
      prefix: rust-nightly

build:host:stable:
  <<: *rust-stable
  stage: build
  needs: []
  script:
    - cargo build

build:host:nightly:
  <<: *rust-nightly
  stage: build
  needs: []
  script:
    - cargo build

build:host:nightly:docs:
  <<: *rust-nightly
  stage: build
  needs: []
  script:
    - cargo doc --no-deps -p harbour-whisperfish -p libsignal-service -p libsignal-protocol -p zkgroup --document-private-items
  artifacts:
    paths:
      - target/doc

qmllint:
  <<: *rust
  stage: format
  image: rust
  cache: {}
  script:
    - "qmllint qml/**/*.qml"

test:stable:
  <<: *rust-stable
  stage: test
  needs:
    - build:host:stable
  script:
    - cargo test

test:stable:diesel-schema:
  <<: *rust-stable
  stage: test
  needs:
    - build:host:stable
  script:
    - cargo install -f diesel_cli
    - rustup component add rustfmt
    - export PATH="$CARGO_HOME/bin:$PATH"
    - export DATABASE_URL=test_whisperfish.db
    - diesel setup
    - diesel migration run
    - diesel print-schema > src/schema.rs
    - cargo fmt -- --check src/schema.rs

test:nightly:
  <<: *rust-nightly
  stage: test
  needs:
    - build:host:nightly
  script:
    - cargo test

fmt:nightly:
  <<: *rust-nightly
  allow_failure: false
  stage: format
  needs:
    - test:nightly
  script:
    - cargo fmt -- --check

coverage:nightly:
  <<: *rust-nightly
  image: xd009642/tarpaulin:develop-nightly
  stage: format
  needs: []
  script:
    - export PATH="$CARGO_HOME/bin:$PATH"
    - cargo tarpaulin -v --exclude-files cargo/* --out Xml
  # tarpaulin needs its own cache
  cache:
    <<: *rust-cache
    key:
      files:
        - Cargo.lock
      prefix: rust-nightly-coverage
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    reports:
      cobertura: cobertura.xml

clippy:
  <<: *rust-stable
  allow_failure: false
  stage: format
  needs:
    - test:stable
  script:
    - rustup component add clippy
    # the following command should be used but needs sailfish SDK
    # - cargo clippy --all-targets --all-features -- -D warnings
    - cargo clippy --all-targets -- -D warnings

.translations: &translations
  image: debian
  needs: []
  before_script:
    - apt-get update
    - apt-get install --no-install-recommends -y git qttools5-dev-tools qt5-default python3 python3-requests curl

translations:check:
  <<: *translations
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
  script:
    - .ci/check-translations.sh

translations:update:
  <<: *translations
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - .ci/update-translations.sh

test:sailfishos:validate-rpms:
  stage: test
  image: registry.gitlab.com/whisperfish/sailo-rs/rpm-validator:latest
  allow_failure: true
  dependencies:
    - build:sailfishos:armv7hl
    - build:sailfishos:aarch64
    - build:sailfishos:i486
  needs:
    - build:sailfishos:armv7hl
    - build:sailfishos:aarch64
    - build:sailfishos:i486
  script:
    - for rpm in RPMS/*.rpm; do rpmvalidation.sh $rpm; done

notify_matrix_build_ready:
  stage: deploy
  image: debian
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  environment:
    name: Whisperfish Matrix channel
    url: $MATRIX_HOME_SERVER
  needs:
    - build:sailfishos:armv7hl
    - build:sailfishos:aarch64
    - build:sailfishos:i486
  before_script:
    - apt-get update
    - apt-get install --no-install-recommends -y git curl jq ca-certificates
  script:
    - .ci/send-matrix-build-notification.sh

pages:
  dependencies:
    - build:host:nightly:docs
  needs:
    - build:host:nightly:docs
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - mkdir -p public
    - mv target/doc public/
  artifacts:
    paths:
      - public

openrepos-deploy:
  stage: deploy
  extends: .openrepos-upload-rpm
  variables:
    OPENREPOS_UPLOAD_RPM_APPNAME:  Whisperfish
    OPENREPOS_UPLOAD_RPM_PLATFORM: SailfishOS
    OPENREPOS_UPLOAD_RPM_CATEGORY: Applications
    OPENREPOS_ACTION_DELAY: 3
  environment:
      name: OpenRepos
      url: https://openrepos.net/content/rubdos/whisperfish
  before_script:
    - mv RPMS/*.rpm .
    - ls *.rpm
  needs:
    - build:sailfishos:armv7hl
    - build:sailfishos:i486
    - build:sailfishos:aarch64
    - test:nightly
  dependencies:
    - build:sailfishos:armv7hl
    - build:sailfishos:i486
    - build:sailfishos:aarch64
  only:
    - tags

dry-run:triage:
  stage: test
  image: ruby:2.4
  script:
    - gem install gitlab-triage
    - gitlab-triage --help
    - gitlab-triage --dry-run --token $PRIVATE_TOKEN --source projects --source-id $CI_PROJECT_PATH
  when: manual

policy:run:
  stage: deploy
  image: ruby:2.4
  script:
    - gem install gitlab-triage
    - gitlab-triage --token $PRIVATE_TOKEN --source projects --source-id $CI_PROJECT_PATH
  when: manual

schedule:policyrun:
  stage: deploy
  image: ruby:2.4
  script:
    - gem install gitlab-triage
    - gitlab-triage --token $PRIVATE_TOKEN --source projects --source-id $CI_PROJECT_PATH
  only:
    - schedules
