---
image: coderus/sailfishos-platform-sdk:3.3.0.14

cache:
  paths:
    - /var/cache/zypp/

stages:
  - prepare
  - build
  - test
  - deploy

.docker:builder: &builder
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: prepare
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - echo "Working around https://github.com/GoogleContainerTools/kaniko/issues/595"
    - rm -f .dockerignore
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.builder --build-arg SFOS_VERSION="$SFOS_VERSION" --destination $CI_REGISTRY_IMAGE/builder-$SFOS_VERSION:$CI_COMMIT_REF_SLUG --cache=true

.sfos330: &sfos330
  variables:
    SFOS_VERSION: 3.3.0.14

.sfos321: &sfos321
  variables:
    SFOS_VERSION: 3.2.1.20

docker:builder:3.2.1.20:
  <<: *sfos321
  <<: *builder

docker:builder:3.3.0.15:
  <<: *sfos330
  <<: *builder

.build: &build
  image: registry.gitlab.com/rubdos/whisperfish/builder-$SFOS_VERSION:$CI_COMMIT_REF_SLUG
  stage: build
  script:
    - echo "Building for $SFOS_VERSION"
    - cargo rpm build

.build:arm: &build-arm
  <<: *build

.build:aarch64: &build-aarch64
  <<: *build

build:3.2.1.20:arm:
  <<: *sfos321
  <<: *build-arm

build:3.3.0.15:arm:
  <<: *sfos330
  <<: *build-arm

build:3.2.1.20:aarch64:
  <<: *sfos321
  <<: *build-aarch64

build:3.3.0.15:aarch64:
  <<: *sfos330
  <<: *build-aarch64
