[package]
name = "harbour-whisperfish"
version = "0.6.0-alpha.1"
authors = ["Ruben De Smet <ruben.de.smet@rubdos.be>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qmetaobject = { version = "0.1.4", git = "https://gitlab.com/rubdos/qmetaobject-sfos-rs", branch = "sailfishos" }
cstr = "0.1.0"
cpp = "0.5"
failure = "0.1.6"

[build-dependencies]
cpp_build = "0.5"
failure = "0.1.6"
dotenv = "0.15"
